### PR TITLE
Make Hue lights flash green on a succesful jailbreak

### PR DESCRIPTION
**Pull request by elihwyma**
Quite frankly, this feature, is, **essential**. I can't put it any other way. I'm honestly surprised it wasn't in the jailbreak from day one. A demonstration of such event can be seen [here](https://twitter.com/elihweilrahc13/status/1331399194859495424?s=20).

In all seriousness, it's fairly simple how it works. I just copied the [Shade](https://github.com/CharlieWhile13/Shade-App) backend into Odyssey, and applied the following logic:

- When you open the app, stores the current online lights 
- Just before ldrestart, will set all lights to green, 100% brightness and on
- After a second, it will set all the lights back to the state from cache
- ldrestart runs

To pair a new bridge, you just press the Home button in the bottom left corner, and a very simple UI will popup. 
image
Hue access tokens are just stored in User Defaults

Please, with all your heart, consider merging this, for the benefit of all Odyssey users :)

### CODE REVIEW

**Comment by emiyl** [comment]
Agreed - devs, please add this. The jailbreak is literally unusable without it.

**Review by tale — APPROVED** [review]
Essential fix for Odyssey!

**Comment by CharlieWhile13** [comment]
Currently working on a quick request to clear paired bridges, and choose what lights it controls, instead of every one :)

**Review by quiprr — APPROVED** [review]
Necessary feature and should've been there from day 1.

**Comment by CharlieWhile13** [comment]
image
Now each light you want to toggle needs to be selected in settings + button to clear paired devices

**Review by emiyl — APPROVED** [review]

**Comment by CharlieWhile13** [comment]
I would like to thank everyone for their continued support in this feature!!!
🥰🥰🥰🥰

**Comment by burritosoftware** [comment]
Very essential and critically needed feature. This should happen.

**Review by burritosoftware — APPROVED** [review]

**Review by sqlstatement — APPROVED** [review]
yes.

**Review by marijuanARM — APPROVED** [review]

**Comment by cbyrne** [comment]
this is what i like to call innovation

**Comment by elihwyma** [comment]
It is with great regret that I will be closing this pull request, thank you to everyone who supported this :)

**Pull request closed without merging**
